-- https://dodona.ugent.be/nl/courses/2088/series/26605/activities/645593457

SELECT
    P.DESCRIPTION,
    P.PRODUCT_CODE,
    M.STATE,
    M.CITY
FROM PRODUCT P
    JOIN MANUFACTURER M ON P.MANUFACTURER_ID = M.MANUFACTURER_ID
WHERE P.QUANTITY_ON_HAND < 500;