-- https://dodona.ugent.be/nl/courses/2088/series/22557/activities/80384076

SELECT
    PC.DESCRIPTION,
    SUM(QUANTITY)
FROM PURCHASE_ORDER PO
    JOIN PRODUCT P ON P.PRODUCT_ID = PO.PRODUCT_ID
    JOIN PRODUCT_CODE PC ON PC.PROD_CODE = P.PRODUCT_CODE
GROUP BY PC.DESCRIPTION
HAVING SUM(QUANTITY) > 500
ORDER BY PC.DESCRIPTION ASC;