-- https://dodona.ugent.be/nl/courses/2088/series/22557/activities/400495191

SELECT
    p.DESCRIPTION,
    SUM(P.PURCHASE_COST * PO.QUANTITY) AS TOTAAL,
    SUM(PO.QUANTITY) AS AANTAL_BESTELD
FROM PURCHASE_ORDER PO
    JOIN PRODUCT P ON P.PRODUCT_ID = PO.PRODUCT_ID
GROUP BY P.DESCRIPTION
HAVING
    SUM(P.PURCHASE_COST * QUANTITY) > 50000
ORDER BY TOTAAL DESC;