-- https://dodona.ugent.be/nl/courses/2088/series/22557/activities/1417550907

SELECT
    C.NAME,
    MAX(PO.QUANTITY) AS MAXIMUM
from PURCHASE_ORDER PO
    JOIN CUSTOMER C ON PO.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.NAME
ORDER BY MAXIMUM DESC;