-- https://dodona.ugent.be/nl/courses/2088/series/22557/activities/181954632

SELECT
    COUNT(DISTINCT MANUFACTURER.NAME)
FROM PURCHASE_ORDER PO
    JOIN PRODUCT P ON P.PRODUCT_ID = PO.PRODUCT_ID
    JOIN MANUFACTURER ON MANUFACTURER.MANUFACTURER_ID = P.MANUFACTURER_ID;