-- https://dodona.ugent.be/nl/courses/2088/series/26607/activities/1394118213

SELECT
    PRODUCT_CODE,
    SUM(QUANTITY_ON_HAND) AS TOTAL
FROM PRODUCT
GROUP BY PRODUCT_CODE
HAVING
    SUM(QUANTITY_ON_HAND) < 1000
ORDER BY TOTAL ASC;