-- https://dodona.ugent.be/nl/courses/2088/series/22557/activities/1984068462

SELECT DISTINCT M.NAME
FROM PURCHASE_ORDER po
    JOIN PRODUCT P ON P.PRODUCT_ID = PO.PRODUCT_ID
    JOIN MANUFACTURER M ON M.MANUFACTURER_ID = P.MANUFACTURER_ID
    JOIN CUSTOMER P ON po.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    C.Name = 'New Enterprises';