-- https://dodona.ugent.be/nl/courses/2088/series/26605/activities/2109472782

SELECT c.NAME, p.DESCRIPTION
FROM PURCHASE_ORDER po
    JOIN PRODUCT p ON po.PRODUCT_ID = p.PRODUCT_ID
    JOIN MANUFACTURER m ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
    JOIN CUSTOMER c ON po.CUSTOMER_ID = c.CUSTOMER_ID
WHERE m.city LIKE 'San%'
ORDER BY c.NAME;