-- https://dodona.ugent.be/nl/courses/2088/series/22556/activities/114990394

SELECT
    P.DESCRIPTION as PRODUCT_DESCRIPTION,
    PC.DESCRIPTION as PRODUCTCODE_DESCRIPTION
from PRODUCT_CODE PC
    JOIN PRODUCT P ON PRODUCT_CODE = PC.PROD_CODE
ORDER BY PC.DESCRIPTION;